name: Sync Repositories Manually

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: "Source GitHub repository in the format owner/repo"
        required: true
      source_branch:
        description: "Branch in the source repository to sync from"
        required: true
      target_branch:
        description: "Branch in the current repository to apply changes to"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_REPOS_TOKEN }}
      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython PyGithub

      - name: Run sync_repos.py script
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_REPOS_TOKEN }}
        run: |
          python sync_repos.py \
            --target-repo ${{ github.repository }} \
            --source-repo https://github.com/${{ github.event.inputs.source_repo }}.git \
            --target-branch ${{ github.event.inputs.target_branch }} \
            --source-branch ${{ github.event.inputs.source_branch }}
