name: Sync Repositories

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: "Target GitHub repository in the format owner/repo"
        required: false
      source_repo:
        description: "Source GitHub repository in the format owner/repo"
        required: false
      source_branch:
        description: "Branch in the source repository to sync from. Example: main"
        required: false
      target_branch:
        description: "Branch in the target repository to apply changes to. Example: main"
        required: false
      simulate_cron:
        description: "Simulate the cron job behavior (true or false)"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "15 16 * * *" # Runs at 9:00 am UTC daily

jobs:
  # Job for scheduled or simulated cron runs
  sync_with_matrix:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event.inputs.simulate_cron == 'true' }}

    strategy:
      matrix:
        include:
          - target_repo: "lsfreitas/target"
            source_repo: "lsfreitas/source"
            target_branch: "main"
            source_branch: "main"
          - target_repo: "lsfreitas/target-repo"
            source_repo: "lsfreitas/source-repo"
            target_branch: "main"
            source_branch: "main"
      fail-fast: false

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.DEFAULT_BRANCH }}
          token: ${{ secrets.AUTO_BACKPORT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython PyGithub

      - name: Run python script with matrix values
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: |
          python .github/scripts/sync_repositories.py \
            --target-repo ${{ matrix.target_repo }} \
            --source-repo ${{ matrix.source_repo }} \
            --target-branch ${{ matrix.target_branch }} \
            --source-branch ${{ matrix.source_branch }}

  # Separate job for manual runs with provided inputs
  sync_manual:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.simulate_cron != 'true' }}

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.DEFAULT_BRANCH }}
          token: ${{ secrets.AUTO_BACKPORT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython PyGithub

      - name: Run python script with manual inputs
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_BACKPORT_TOKEN }}
        run: |
          python .github/scripts/sync_repositories.py \
            --target-repo ${{ github.event.inputs.target_repo }} \
            --source-repo ${{ github.event.inputs.source_repo }} \
            --target-branch ${{ github.event.inputs.target_branch }} \
            --source-branch ${{ github.event.inputs.source_branch }}
