name: Sync Repositories

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC (adjust as needed)

jobs:
  sync_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub GitPython

      - name: Run the sync script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          TARGET_REPO_URL: git@github.com:lsfreitas/target-repo.git
          SOURCE_REPO_URL: git@github.com:lsfreitas/source-repo.git
          TARGET_BRANCH: main
          SOURCE_BRANCH: main
        run: |
          python sync_repositories.py
